 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: BWB                                                         
     # Surfaces =   1
     # Strips   = 100
     # Vortices =1200

  Sref =  7840.0       Cref =  30.730       Bref =  280.00    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.131     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.01306     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.30522
  CZtot =  -0.08535     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.08556
  CDtot =   0.01157
  CDvis =   0.00980     CDind =   0.00177
  CLff  =   0.08553     CDff  =   0.00180    | Trefftz
  CYff  =   0.00000         e =    0.1296    | Plane  

   flaperon1       =   0.00000
   flaperon2       =   0.00000
   flaperon3       =   0.00000
   flaperon4       =   0.00000
   flaperon5       =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   6.845015    CLb =  -0.050501
 y  force CY |    CYa =   0.000000    CYb =   0.000000
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.000000
 y  mom.  Cm |    Cma = -18.500111    Cmb =   0.242066
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =  -0.000000

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.491634    CLq =  52.250500    CLr =   0.038955
 y  force CY |    CYp =   0.000000    CYq =   0.000000    CYr =  -0.000000
 x' mom.  Cl'|    Clp =  -0.000000    Clq =  -0.000000    Clr =   0.000000
 y  mom.  Cm |    Cmp =  -7.603732    Cmq =-151.372055    Cmr =  -0.146626
 z' mom.  Cn'|    Cnp =  -0.000000    Cnq =  -0.000000    Cnr =   0.000000

                  flaperon1    d1     flaperon2    d2     flaperon3    d3     flaperon4    d4     flaperon5    d5 
                  ----------------    ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.005439   CLd2 =   0.009964   CLd3 =   0.005795   CLd4 =   0.002047   CLd5 =   0.001584
 y  force CY |   CYd1 =   0.000000   CYd2 =   0.000000   CYd3 =   0.000000   CYd4 =   0.000000   CYd5 =   0.000000
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =  -0.000000   Cld3 =  -0.000000   Cld4 =  -0.000000   Cld5 =  -0.000000
 y  mom.  Cm |   Cmd1 =  -0.019095   Cmd2 =  -0.032821   Cmd3 =  -0.020732   Cmd4 =  -0.007923   Cmd5 =  -0.006437
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =  -0.000000   Cnd3 =  -0.000000   Cnd4 =  -0.000000   Cnd5 =  -0.000000
 Trefftz drag| CDffd1 =   0.000102 CDffd2 =  -0.000032 CDffd3 =  -0.000085 CDffd4 =  -0.000038 CDffd5 =  -0.000042
 span eff.   |    ed1 =   0.009142    ed2 =   0.032503    ed3 =   0.023686    ed4 =   0.008952    ed5 =   0.007827



 Neutral point  Xnp =  83.054375
