 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: BWB                                                         
     # Surfaces =   1
     # Strips   = 100
     # Vortices =1200

  Sref =  7840.0       Cref =  30.730       Bref =  280.00    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.131     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.06237     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -2.87016
  CZtot =  -1.03330     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.03320
  CDtot =   0.06402
  CDvis =   0.02366     CDind =   0.04036
  CLff  =   1.03786     CDff  =   0.04129    | Trefftz
  CYff  =   0.00000         e =    0.8304    | Plane  

   flaperon1       =   0.00000
   flaperon2       =   0.00000
   flaperon3       =   0.00000
   flaperon4       =   0.00000
   flaperon5       =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   6.677460    CLb =  -0.158369
 y  force CY |    CYa =   0.000000    CYb =  -0.000000
 x' mom.  Cl'|    Cla =  -0.000000    Clb =   0.000000
 y  mom.  Cm |    Cma = -18.031750    Cmb =   0.724322
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.000000

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.482995    CLq =  52.491486    CLr =  -0.569591
 y  force CY |    CYp =  -0.000000    CYq =   0.000000    CYr =   0.000000
 x' mom.  Cl'|    Clp =   0.000000    Clq =  -0.000000    Clr =  -0.000000
 y  mom.  Cm |    Cmp =  -7.482686    Cmq =-151.458344    Cmr =   1.893706
 z' mom.  Cn'|    Cnp =   0.000000    Cnq =  -0.000000    Cnr =  -0.000000

                  flaperon1    d1     flaperon2    d2     flaperon3    d3     flaperon4    d4     flaperon5    d5 
                  ----------------    ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.005266   CLd2 =   0.009808   CLd3 =   0.005695   CLd4 =   0.002001   CLd5 =   0.001549
 y  force CY |   CYd1 =   0.000000   CYd2 =   0.000000   CYd3 =   0.000000   CYd4 =   0.000000   CYd5 =   0.000000
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =  -0.000000   Cld3 =  -0.000000   Cld4 =  -0.000000   Cld5 =  -0.000000
 y  mom.  Cm |   Cmd1 =  -0.018641   Cmd2 =  -0.032388   Cmd3 =  -0.020322   Cmd4 =  -0.007715   Cmd5 =  -0.006269
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =  -0.000000   Cnd3 =  -0.000000   Cnd4 =  -0.000000   Cnd5 =  -0.000000
 Trefftz drag| CDffd1 =   0.000540 CDffd2 =   0.000402 CDffd3 =   0.000098 CDffd4 =   0.000037 CDffd5 =   0.000037
 span eff.   |    ed1 =  -0.002307    ed2 =   0.007690    ed3 =   0.007145    ed4 =   0.002468    ed5 =   0.001744



 Neutral point  Xnp =  82.982994
