 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: BWB                                                         
     # Surfaces =   1
     # Strips   = 100
     # Vortices =1200

  Sref =  7840.0       Cref =  30.730       Bref =  280.00    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  14.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.131     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10171     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -5.24338
  CZtot =  -1.90845     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.82716
  CDtot =   0.56038
  CDvis =   0.44093     CDind =   0.11945
  CLff  =   1.85521     CDff  =   0.12503    | Trefftz
  CYff  =   0.00000         e =    0.8762    | Plane  

   flaperon1       =   0.00000
   flaperon2       =   0.00000
   flaperon3       =   0.00000
   flaperon4       =   0.00000
   flaperon5       =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   6.333560    CLb =  -0.242060
 y  force CY |    CYa =   0.000000    CYb =  -0.000000
 x' mom.  Cl'|    Cla =  -0.000000    Clb =   0.000000
 y  mom.  Cm |    Cma = -18.494276    Cmb =   1.137492
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.000000

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.641783    CLq =  55.566734    CLr =  -1.055573
 y  force CY |    CYp =  -0.000000    CYq =   0.000000    CYr =   0.000000
 x' mom.  Cl'|    Clp =   0.000000    Clq =  -0.000000    Clr =  -0.000000
 y  mom.  Cm |    Cmp =  -7.889641    Cmq =-163.176346    Cmr =   3.925572
 z' mom.  Cn'|    Cnp =   0.000000    Cnq =  -0.000000    Cnr =  -0.000000

                  flaperon1    d1     flaperon2    d2     flaperon3    d3     flaperon4    d4     flaperon5    d5 
                  ----------------    ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.004912   CLd2 =   0.009351   CLd3 =   0.005431   CLd4 =   0.001898   CLd5 =   0.001468
 y  force CY |   CYd1 =   0.000000   CYd2 =   0.000000   CYd3 =   0.000000   CYd4 =   0.000000   CYd5 =   0.000000
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =  -0.000000   Cld3 =  -0.000000   Cld4 =  -0.000000   Cld5 =  -0.000000
 y  mom.  Cm |   Cmd1 =  -0.017938   Cmd2 =  -0.032614   Cmd3 =  -0.020372   Cmd4 =  -0.007635   Cmd5 =  -0.006166
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =  -0.000000   Cnd3 =  -0.000000   Cnd4 =  -0.000000   Cnd5 =  -0.000000
 Trefftz drag| CDffd1 =   0.000886 CDffd2 =   0.000756 CDffd3 =   0.000249 CDffd4 =   0.000097 CDffd5 =   0.000101
 span eff.   |    ed1 =  -0.001332    ed2 =   0.003781    ed3 =   0.003480    ed4 =   0.001144    ed5 =   0.000709



 Neutral point  Xnp =  89.732956
