 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: BWB                                                         
     # Surfaces =   1
     # Strips   = 100
     # Vortices =1200

  Sref =  7840.0       Cref =  30.730       Bref =  280.00    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  12.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.131     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.00579     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -4.51168
  CZtot =  -1.64003     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.60539
  CDtot =   0.33531
  CDvis =   0.24223     CDind =   0.09309
  CLff  =   1.62398     CDff  =   0.09668    | Trefftz
  CYff  =   0.00000         e =    0.8683    | Plane  

   flaperon1       =   0.00000
   flaperon2       =   0.00000
   flaperon3       =   0.00000
   flaperon4       =   0.00000
   flaperon5       =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   6.438482    CLb =  -0.219498
 y  force CY |    CYa =   0.000000    CYb =  -0.000000
 x' mom.  Cl'|    Cla =  -0.000000    Clb =   0.000000
 y  mom.  Cm |    Cma = -18.090065    Cmb =   1.025125
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.000000

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.551339    CLq =  54.131062    CLr =  -0.928774
 y  force CY |    CYp =  -0.000000    CYq =   0.000000    CYr =   0.000000
 x' mom.  Cl'|    Clp =   0.000000    Clq =  -0.000000    Clr =  -0.000000
 y  mom.  Cm |    Cmp =  -7.612950    Cmq =-157.293442    Cmr =   3.266304
 z' mom.  Cn'|    Cnp =   0.000000    Cnq =  -0.000000    Cnr =  -0.000000

                  flaperon1    d1     flaperon2    d2     flaperon3    d3     flaperon4    d4     flaperon5    d5 
                  ----------------    ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.005031   CLd2 =   0.009511   CLd3 =   0.005523   CLd4 =   0.001933   CLd5 =   0.001496
 y  force CY |   CYd1 =   0.000000   CYd2 =   0.000000   CYd3 =   0.000000   CYd4 =   0.000000   CYd5 =   0.000000
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =  -0.000000   Cld3 =  -0.000000   Cld4 =  -0.000000   Cld5 =  -0.000000
 y  mom.  Cm |   Cmd1 =  -0.018151   Cmd2 =  -0.032429   Cmd3 =  -0.020238   Cmd4 =  -0.007607   Cmd5 =  -0.006155
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =  -0.000000   Cnd3 =  -0.000000   Cnd4 =  -0.000000   Cnd5 =  -0.000000
 Trefftz drag| CDffd1 =   0.000792 CDffd2 =   0.000659 CDffd3 =   0.000207 CDffd4 =   0.000081 CDffd5 =   0.000083
 span eff.   |    ed1 =  -0.001528    ed2 =   0.004453    ed3 =   0.004113    ed4 =   0.001367    ed5 =   0.000874



 Neutral point  Xnp =  86.341415
