 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: BWB                                                         
     # Surfaces =   1
     # Strips   = 100
     # Vortices =1200

  Sref =  7840.0       Cref =  30.730       Bref =  280.00    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.131     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.01006     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =   0.01745
  CZtot =   0.03428     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =  -0.03390
  CDtot =   0.01125
  CDvis =   0.01004     CDind =   0.00121
  CLff  =  -0.03401     CDff  =   0.00126    | Trefftz
  CYff  =   0.00000         e =    0.0292    | Plane  

   flaperon1       =   0.00000
   flaperon2       =   0.00000
   flaperon3       =   0.00000
   flaperon4       =   0.00000
   flaperon5       =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   6.843882    CLb =  -0.036487
 y  force CY |    CYa =   0.000000    CYb =   0.000000
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.000000
 y  mom.  Cm |    Cma = -18.471046    Cmb =   0.181453
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =  -0.000000

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.489608    CLq =  52.266273    CLr =   0.114880
 y  force CY |    CYp =   0.000000    CYq =   0.000000    CYr =  -0.000000
 x' mom.  Cl'|    Clp =  -0.000000    Clq =  -0.000000    Clr =   0.000000
 y  mom.  Cm |    Cmp =  -7.584824    Cmq =-151.247025    Cmr =  -0.401991
 z' mom.  Cn'|    Cnp =  -0.000000    Cnq =  -0.000000    Cnr =   0.000000

                  flaperon1    d1     flaperon2    d2     flaperon3    d3     flaperon4    d4     flaperon5    d5 
                  ----------------    ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.005441   CLd2 =   0.009955   CLd3 =   0.005792   CLd4 =   0.002047   CLd5 =   0.001584
 y  force CY |   CYd1 =   0.000000   CYd2 =   0.000000   CYd3 =   0.000000   CYd4 =   0.000000   CYd5 =   0.000000
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =  -0.000000   Cld3 =  -0.000000   Cld4 =  -0.000000   Cld5 =  -0.000000
 y  mom.  Cm |   Cmd1 =  -0.019103   Cmd2 =  -0.032799   Cmd3 =  -0.020737   Cmd4 =  -0.007931   Cmd5 =  -0.006444
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =  -0.000000   Cnd3 =  -0.000000   Cnd4 =  -0.000000   Cnd5 =  -0.000000
 Trefftz drag| CDffd1 =   0.000045 CDffd2 =  -0.000087 CDffd3 =  -0.000108 CDffd4 =  -0.000048 CDffd5 =  -0.000052
 span eff.   |    ed1 =  -0.010391    ed2 =  -0.015095    ed3 =  -0.007437    ed4 =  -0.002401    ed5 =  -0.001505



 Neutral point  Xnp =  82.937622
