 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: BWB                                                         
     # Surfaces =   1
     # Strips   = 100
     # Vortices =1200

  Sref =  7840.0       Cref =  30.730       Bref =  280.00    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.131     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.00498     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -1.59560
  CZtot =  -0.56283     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.56232
  CDtot =   0.02449
  CDvis =   0.01089     CDind =   0.01359
  CLff  =   0.56307     CDff  =   0.01378    | Trefftz
  CYff  =   0.00000         e =    0.7324    | Plane  

   flaperon1       =   0.00000
   flaperon2       =   0.00000
   flaperon3       =   0.00000
   flaperon4       =   0.00000
   flaperon5       =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   6.800035    CLb =  -0.105599
 y  force CY |    CYa =   0.000000    CYb =  -0.000000
 x' mom.  Cl'|    Cla =  -0.000000    Clb =   0.000000
 y  mom.  Cm |    Cma = -18.411762    Cmb =   0.483662
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.000000

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.492200    CLq =  52.278008    CLr =  -0.265614
 y  force CY |    CYp =  -0.000000    CYq =   0.000000    CYr =   0.000000
 x' mom.  Cl'|    Clp =   0.000000    Clq =  -0.000000    Clr =  -0.000000
 y  mom.  Cm |    Cmp =  -7.601192    Cmq =-151.563156    Cmr =   0.876834
 z' mom.  Cn'|    Cnp =   0.000000    Cnq =  -0.000000    Cnr =  -0.000000

                  flaperon1    d1     flaperon2    d2     flaperon3    d3     flaperon4    d4     flaperon5    d5 
                  ----------------    ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.005385   CLd2 =   0.009937   CLd3 =   0.005773   CLd4 =   0.002034   CLd5 =   0.001574
 y  force CY |   CYd1 =   0.000000   CYd2 =   0.000000   CYd3 =   0.000000   CYd4 =   0.000000   CYd5 =   0.000000
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =  -0.000000   Cld3 =  -0.000000   Cld4 =  -0.000000   Cld5 =  -0.000000
 y  mom.  Cm |   Cmd1 =  -0.018952   Cmd2 =  -0.032739   Cmd3 =  -0.020610   Cmd4 =  -0.007850   Cmd5 =  -0.006379
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =  -0.000000   Cnd3 =  -0.000000   Cnd4 =  -0.000000   Cnd5 =  -0.000000
 Trefftz drag| CDffd1 =   0.000324 CDffd2 =   0.000187 CDffd3 =   0.000007 CDffd4 =  -0.000001 CDffd5 =  -0.000002
 span eff.   |    ed1 =  -0.003184    ed2 =   0.015900    ed3 =   0.014597    ed4 =   0.005301    ed5 =   0.004209



 Neutral point  Xnp =  83.204491
