 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: BWB                                                         
     # Surfaces =   1
     # Strips   = 100
     # Vortices =1200

  Sref =  7840.0       Cref =  30.730       Bref =  280.00    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.131     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.06330     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -3.83269
  CZtot =  -1.38938     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.37926
  CDtot =   0.17893
  CDvis =   0.10932     CDind =   0.06961
  CLff  =   1.39077     CDff  =   0.07181    | Trefftz
  CYff  =   0.00000         e =    0.8574    | Plane  

   flaperon1       =   0.00000
   flaperon2       =   0.00000
   flaperon3       =   0.00000
   flaperon4       =   0.00000
   flaperon5       =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   6.541504    CLb =  -0.195798
 y  force CY |    CYa =   0.000000    CYb =  -0.000000
 x' mom.  Cl'|    Cla =  -0.000000    Clb =   0.000000
 y  mom.  Cm |    Cma = -17.904369    Cmb =   0.908589
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.000000

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.500375    CLq =  53.163548    CLr =  -0.790954
 y  force CY |    CYp =  -0.000000    CYq =   0.000000    CYr =   0.000000
 x' mom.  Cl'|    Clp =   0.000000    Clq =  -0.000000    Clr =  -0.000000
 y  mom.  Cm |    Cmp =  -7.467126    Cmq =-153.477615    Cmr =   2.678935
 z' mom.  Cn'|    Cnp =   0.000000    Cnq =  -0.000000    Cnr =  -0.000000

                  flaperon1    d1     flaperon2    d2     flaperon3    d3     flaperon4    d4     flaperon5    d5 
                  ----------------    ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.005136   CLd2 =   0.009648   CLd3 =   0.005601   CLd4 =   0.001963   CLd5 =   0.001520
 y  force CY |   CYd1 =   0.000000   CYd2 =   0.000000   CYd3 =   0.000000   CYd4 =   0.000000   CYd5 =   0.000000
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =  -0.000000   Cld3 =  -0.000000   Cld4 =  -0.000000   Cld5 =  -0.000000
 y  mom.  Cm |   Cmd1 =  -0.018355   Cmd2 =  -0.032314   Cmd3 =  -0.020166   Cmd4 =  -0.007604   Cmd5 =  -0.006166
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =  -0.000000   Cnd3 =  -0.000000   Cnd4 =  -0.000000   Cnd5 =  -0.000000
 Trefftz drag| CDffd1 =   0.000694 CDffd2 =   0.000558 CDffd3 =   0.000165 CDffd4 =   0.000063 CDffd5 =   0.000065
 span eff.   |    ed1 =  -0.001780    ed2 =   0.005383    ed3 =   0.004987    ed4 =   0.001680    ed5 =   0.001112



 Neutral point  Xnp =  84.109291
